config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'welcome#index'
      resources :pages
      resources :contents
      resources :graphics
      get '/controls', to: 'controls#index'
      post '/pages/add-content', to: 'pages#add_content'
      post '/pages/remove-content', to: 'pages#remove_content'
      post '/pages/add-graphic', to: 'pages#add_graphic'
      post '/pages/remove-graphic', to: 'pages#remove_graphic'
    end
    unauthenticated :user do
      root 'welcome#index', as: :unauthenticated_root
      get '/pages/(*all)', to: redirect('/')
      get '/contents/(*all)', to: redirect('/')
      get '/graphics/(*all)', to: redirect('/')
    end
  end

  get 'trivia/' => 'welcome#trivia'

end

app/models/content.rb
class Content < ActiveRecord::Base
  validates_format_of :identifier, with: /\A^\S+$\z/, on: :create
  validates_uniqueness_of :identifier
  has_and_belongs_to_many :pages, :join_table => :contents_pages
end

app/models/graphic.rb
class Graphic < ActiveRecord::Base
  validates_format_of :identifier, with: /\A^\S+$\z/, on: :create
  validates_uniqueness_of :identifier
  has_and_belongs_to_many :pages, :join_table => :graphics_pages
  mount_uploader :image, ImageUploader
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates_uniqueness_of :controller, :scope => :action
  has_and_belongs_to_many :contents, :join_table => :contents_pages
  has_and_belongs_to_many :graphics, :join_table => :graphics_pages
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :defaults

  def defaults
    self.role ||= "client"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :get_pages
  layout :layout_by_resource
  before_filter :update_sanitized_params, if: :devise_controller?

  def after_sign_in_path_for user
    controls_path
  end

  def after_account_update_path_for user
    controls_path
  end

  def get_pages
    if session
      @pages = Page.all
    end
  end

  private

  def get_contents page
    contents = {}
    page.contents.each do |c|
      contents[c.identifier] = c
    end
    return contents
  end

  def get_graphics page
    graphics = {}
    page.graphics.each do |g|
      graphics[g.identifier] = g
    end
    return graphics
  end

  protected

  def layout_by_resource
    if devise_controller?
      "users_custom"
    else
      "application"
    end
  end

  def update_sanitized_params
    devise_parameter_sanitizer.for(:account_update) << :role
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @contents = Content.all
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      flash[:notice] = "Your new content has been created."
      redirect_to contents_path
    else
      render "new"
    end
  end

  def edit
    @content = Content.find(params[:id])
  end

  def update
    @content = Content.find(params[:id])
    if @content.update_attributes(content_params)
      flash[:notice] = "Your content has been updated."
      redirect_to contents_path
    else
      render "edit"
    end
  end

  def destroy
    @content = Content.find(params[:id])
    if @content.destroy
      redirect_to contents_path, :notice => "The content has been deleted."
    else
      redirect_to contents_path, :notice => "The content could not be deleted."
    end
  end

  private

  def content_params
    params.require(:content).permit(:text, :identifier)
  end
end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController
  def index
  end
end

app/controllers/graphics_controller.rb
class GraphicsController < ApplicationController
  def index
    @graphics = Graphic.all
  end

  def new
    @graphic = Graphic.new
  end

  def create
    @graphic = Graphic.new(graphic_params)
    if @graphic.save
      flash[:notice] = "Graphic with identifier #{@graphic.identifier} has been created"
      redirect_to graphics_path
    else
      render "new"
    end
  end

  def edit
    @graphic = Graphic.find(params[:id])
  end

  def update
    @graphic = Graphic.find(params[:id])
    if @graphic.update_attributes(graphic_params)
      flash[:notice] = "Graphic with identifier #{@graphic.identifier} has been updated."
      redirect_to graphics_path
    else
      render "edit"
    end
  end

  def destroy
    @graphic = Graphic.find(params[:id])
    identifier = @graphic.identifier
    if @graphic.destroy
      flash[:notice] = "The graphic with identifier #{identifier} has been deleted."
      redirect_to graphics_path
    else
      flash[:notice] = "The graphic with identifier #{identifier} could not be deleted."
      redirect_to graphics_path
    end
  end

  private

  def graphic_params
    params.require(:graphic).permit(:identifier, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      flash[:notice] = "The new page has been created for #{page_params[:controller]}##{page_params[:action]}"
      redirect_to pages_path
    else
      render "new"
    end
  end

  def edit
    @page = Page.find(params[:id])
    @contents = Content.all
    @graphics = Graphic.all
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(page_params)
      flash[:notice] = "Page at #{@page.controller}##{@page.action} has been updated."
      redirect_to pages_path
    else
      render "edit"
    end
  end

  def destroy
    @page = Page.find(params[:id])
    controller = @page.controller
    action = @page.action
    if @page.destroy
      redirect_to pages_path, :notice => "Page at #{controller}##{action} has been deleted."
    else
      redirect_to pages_path, :notice => "Page at #{controller}##{action} could not be deleted."
    end
  end

  def add_content
    @page = Page.find(params[:pageId])
    @content = Content.find(params[:contentId])
    @errors = []
    if !@page.contents.exists? @content
      @page.contents << @content
    else
      @errors << "Page already contains that content."
    end
    respond_to do |format|
      format.js
    end
  end

  def remove_content
    @page = Page.find(params[:pageId])
    @page.contents.delete(params[:contentId])
    respond_to do |format|
      format.js
    end
  end

  def add_graphic
    @page = Page.find(params[:pageId])
    @graphic = Graphic.find(params[:graphicId])
    @errors = []
    if !@page.graphics.exists? @graphic
      @page.graphics << @graphic
    else
      @errors << "Page already contains that graphic."
    end
    respond_to do |format|
      format.js
    end
  end

  def remove_graphic
    @page = Page.find(params[:pageId])
    @page.graphics.delete(params[:graphicId])
    respond_to do |format|
      format.js
    end
  end

  private
  def page_params
    params.require(:page).permit(:title, :controller, :action)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @page = Page.find_by(controller: params[:controller], action: params[:action])
    @contents = get_contents @page
    @graphics = get_graphics @page
  end

  def trivia
    @page = Page.find_by(controller: params[:controller], action: params[:action])
    @contents = get_contents @page
    @graphics = get_graphics @page
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/helpers/graphics_helper.rb
module GraphicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contents/edit.html.haml
.row
  .col-xs-3
  .col-xs-6.admin-text
    =form_for @content do |f|
      %fieldset
        %legend Edit A Content
        =if @content.errors.any?
          %h2 Errors:
          %ul
            = @content.errors.full_messages.each do |m|
              %li=m
        .row
          .col-xs-4
            - if current_user.role == "admin"
              =f.label :text
            %p
              %small
                Basic HTML tags supported. Be careful with any that could affect the page layout, such as &ltdiv&gt.
                Recommended tags would include: &lta href = "whatever.com/whatever"&gtstuff&lt/a&gt (Makes a link).
                <a href="http://www.w3schools.com/tags/" target="new">W3 Schools</a> is an excellent reference.
          .col-xs-4
            =f.text_area :text, :cols => 20, :rows => 7
          .col-xs-4
        - if current_user.role == "admin"
          .row
            .col-xs-4
              =f.label :identifier
            .col-xs-4
              =f.text_field :identifier
            .col-xs-4
        .row
          .col-xs-12
            =f.submit "Update This Content"
  .col-xs-3

app/views/contents/index.html.haml
.row
  .col-xs-12
    - column = 0
    - @contents.each do |content|
      - if column % 3 == 0
        .row
      .col-xs-4.admin-text
        %h5= content.identifier
        .row
          .col-xs-12
            %p
              =render inline: content.text
            - if content.pages
              - string = "On Pages:"
              - content.pages.each do |page|
                - string += " <a href='pages/#{page.id}/edit'>#{page.controller}##{page.action}</a>"
              %p
                =render inline: string
        .row
          .col-xs-12
            = button_to "Edit", edit_content_path(content.id), :method => :get
            - if current_user.role == "admin"
              = button_to "Delete", content, data: { confirm: "Are you sure you want to delete this content?" }, :method => :delete
      - column = column + 1

app/views/contents/new.html.haml
.row
  .col-xs-3
  .col-xs-6.admin-text
    = form_for @content do |f|
      %fieldset
        %legend Create a Content
        = if @content.errors.any?
          .row
            .col-xs-12
              %h2 Errors:
              %ul
                = @content.errors.full_messages.each do |m|
                  %li=m
        .row
          .col-xs-4
            =f.label :text
          .col-xs-4
            =f.text_area :text, :cols => 20, :rows => 7
          .col-xs-4
        .row
          .col-xs-4
            =f.label :identifier do
              Identifier <small class="asterisk">*</small>
          .col-xs-4
            =f.text_field :identifier, :required => true
          .col-xs-4
        .row
          .col-xs-12
            =f.submit "Create A Content"
        .row
          .col-xs-12
            %label.required-label
              %small.asterisk * required
  .col-xs-3

app/views/controls/index.html.haml
.row
  .col-xs-2
  .col-xs-8.controls-index-heading
    %h1.admin-text Welcome to Your Site's Control Panel
  .col-xs-2
.row
  .col-xs-4.admin-text
    %p.controls-index-intro
      Here is where you can change certain aspects of your site, such as text and images. On the right, you will see descriptions of each of
      the menus on your dashboard. Some of the terms you will see:
    %p
      <strong>Pages</strong> represent the different pages of your site, such as your homepage and "whatever.com/dogs", for example.
    %p
      <strong>Contents</strong> represent the different blocks of text on your webpages.
    %p
      <strong>Graphics</strong> represent the different images that appear throughout your site.
  .col-xs-8
    .row
      .col-xs-4.admin-text.controls-index-menu-desc
        %h4 Pages
        %p
          %strong Manage
          will allow you to see a listing of the pages of your site. Click an edit button to manage the contents of that page.
        %p
          %strong View
          will allow you to view your pages as any visitor would but with your dashboard at the top of the screen.
        %p
          A page is listed by what's called it's <strong>controller</strong> and it's <strong> action</strong>. Ex: your homepage is usually
          <strong>welcome#index</strong>. It's controller is <strong>welcome</strong> and it's action is <strong>index</strong>.
        %p
          If you had a page showing dogs, it would be <strong>dogs#index</strong>.
          A link to information on a specific dog would be <strong>dogs#show</strong>.
          This is the basic structure of most websites.
      .col-xs-4.admin-text.controls-index-menu-desc
        %h4 Contents
        %p
          Lists all the different blocks of text on your site for editing. This is a good menu to use to edit text that appears on more than
          one page.
        %p
          Contents, like graphics, are listed by their <strong>identifiers</strong>, which let your web browser know where to put and what to do with
          them.
        %p
          For example, if you owned a store and wanted to change your hours of operation, the <strong>identifier</strong> for that content
          would most likely be <strong>hours-of-operation</strong>.
        %p
          Each content listing will include the pages on your site on which it resides, listed by
          <strong>controller</strong> and <strong>action</strong>.
      .col-xs-4.admin-text.controls-index-menu-desc
        %h4 Graphics
        %p
          Lists all the different images used on your website that can be changed.
        %p
          Graphics, like contents, are listed by their <strong>identifiers</strong>. If you were to "open up the hood" on your site, you would
          see that these identifiers also contain instructions to a web browser on exactly where to put and how to size the images they represent.
        %p
          For example, if you wanted to change your company's logo, you would just have to find the graphic with an <strong>identifier</strong>
          named <strong>company-logo</strong>, or <strong>brand-image</strong>, etc.
        %p
          Each graphic listing will include the pages on your site that display this image, listed by <strong>controller</strong>
          and <strong>action</strong>.

app/views/graphics/edit.html.haml
.row
  .col-xs-3
  .col-xs-6.admin-text
    = form_for @graphic, html: { multipart: true } do |f|
      %fieldset
        %legend Edit a Graphic
        .row
          .col-xs-12.graphic-edit-image-display
            =image_tag(asset_path(@graphic.image))
        = if @graphic.errors.any?
          .row
            .col-xs-12
              %h2 Errors:
              %ul
                = @graphic.errors.full_messages.each do |m|
                  %li=m
        - if current_user.role == "admin"
          .row
            .col-xs-4
              =f.label :identifier do
                Identifier <small class="asterisk">*</small>
            .col-xs-4
              =f.text_field :identifier, :require => true
            .col-xs-4
        .row
          .col-xs-4
            =f.label :image do
              Change The Image
          .col-xs-4
            =f.file_field :image
          .col-xs-4
        .row
          .col-xs-12
            =f.submit "Update the Graphic"
    .col-xs-3

app/views/graphics/index.html.haml
.row
  .col-xs-12
    - column = 0
    - @graphics.each do |graphic|
      - if column % 3 == 0
        .row
      .col-xs-4.graphics-index-cell.admin-text
        .row
          .col-xs-12
            %h5=graphic.identifier
            =image_tag(asset_path(graphic.image), class: "graphics-index-pic")
        .row
          .col-xs-12
            - if graphic.pages
              - string = "On Pages:"
              - graphic.pages.each do |page|
                - string += " <a href='pages/#{page.id}/edit'>#{page.controller}##{page.action}</a>"
              %p
                =render inline: string
        .row
          .col-xs-12
            = button_to "Edit", edit_graphic_path(graphic.id), :method => :get
            - if current_user.role == "admin"
              = button_to "Delete", graphic, data: {confirm: "Are you sure you want to delete the graphic?"}, :method => :delete
      - column = column + 1

app/views/graphics/new.html.haml
.row
  .col-xs-3
  .col-xs-6.admin-text
    = form_for @graphic, html: { multipart: true } do |f|
      %fieldset
        %legend Upload a Graphic
        = if @graphic.errors.any?
          .row
            .col-xs-12
              %h2 Errors:
              %ul
                = @graphic.errors.full_messages.each do |m|
                  %li=m
        .row
          .col-xs-4
            =f.label :identifier do
              Identifier <small class="asterisk">*</small>
          .col-xs-4
            =f.text_field :identifier, :require => true
          .col-xs-4
        .row
          .col-xs-4
            =f.label :image do
              Upload An Image <small class="asterisk">*</small>
          .col-xs-4
            =f.file_field :image, :required => true
          .col-xs-4
        .row
          .col-xs-12
            =f.submit "Create A Graphic"
        .row
          .col-xs-12
            %label.required-label
              %small.asterisk * required
  .col-xs-3

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if @page %>
    <title><%= @page.title %></title>
  <% else %>
    <title>Dremplate</title>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">

  <% if user_signed_in? %>
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Dremplate</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/controls">Control Panel Home</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#"><strong>Manage:</strong></a></li>
              <li><a href="/pages">Edit</a></li>

              <% if current_user.role == "admin" %>
                <li><a href="/pages/new">Create New</a></li>
              <% end %>

              <li class="divider"></li>
              <li><a href="#"><strong>View:</strong></a></li>
              <% if @pages %>
                <% @pages.each do |page| %>
                  <li>
                    <%= link_to("#{page.title} | #{page.controller}##{page.action}", :controller => page.controller, :action => page.action) %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contents <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/contents">Edit</a></li>
              <% if current_user.role == "admin" %>
                <li><a href="/contents/new">Create New</a></li>
              <% end %>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Graphics<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/graphics">Edit</a></li>
              <% if current_user.role == "admin" %>
                <li><a href="/graphics/new">Create New</a></li>
              <% end %>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Me<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/users/edit">Edit</a></li>

              <% if current_user.role == "admin" %>
                <li><a href="/users/sign_up">Sign Up</a></li>
              <% end %>

            </ul>
          </li>
          <li class="active">
            <% if user_signed_in? %>
              <%= link_to("Sign Out", destroy_user_session_path, :method => :delete) %>
            <% else %>
              <a href="/users/sign_in">Sign In</a>
            <% end %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
  <% end %>

  <% if flash[:notice] %>
    <div class="row">
      <div class="col-xs-12">
        <p class="notice">
          <%= flash[:notice] %>
        </p>
      </div>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="row">
      <div class="col-xs-12">
        <p class="alert">
          <%= flash[:alert] %>
        </p>
      </div>
    </div>
  <% end %>

  <%= yield %>

  <div>
    <% if !user_signed_in? %>
      <a href="/users/sign_in">Control Panel</a>
    <% end %>
  </div>
</div>

</body>
</html>

app/views/layouts/users_custom.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dremplate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">

  <% if user_signed_in? %>
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Dremplate</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/controls">Control Panel Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Me<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/users/edit">Edit</a></li>
              <% if current_user.role == "admin" %>
                <li><a href="/users/sign_up">Sign Up</a></li>
              <% end %>
            </ul>
          </li>
          <li class="active">
            <% if user_signed_in? %>
              <%= link_to("Sign Out", destroy_user_session_path, :method => :delete) %>
            <% else %>
              <a href="/users/sign_in">Sign In</a>
            <% end %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
  <% end %>

  <% if flash[:notice] %>
    <div class="row">
      <div class="col-xs-12">
        <p class="notice">
          <%= flash[:notice] %>
        </p>
      </div>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="row">
      <div class="col-xs-12">
        <p class="alert">
          <%= flash[:alert] %>
        </p>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-4"></div>
    <div class="col-xs-4 admin-text">
      <%= yield %>
    </div>
    <div class="col-xs-4"></div>

</div>

</body>
</html>

app/views/pages/_contents_list.html.haml
- if @errors
  %ul
    - @errors.each do |error|
      %li
        %p.alert=error
- if @page.contents
  %ul
    - @page.contents.each do |content|
      %li
        %strong=link_to "#{content.identifier}", edit_content_path(content)

        - if current_user.role == "admin"
          %button.remove-content{ :data => { :page_id => @page.id, :content_id => content.id } } Remove

        %p
          =render inline: content.text

app/views/pages/_graphics_list.html.haml
- if @errors
  %ul
    - @errors.each do |error|
      %li
        %p.alert=error
- if @page.graphics
  - @page.graphics.each do |graphic|
    .row
      .col-xs-1
      .col-xs-5
        %strong=link_to "#{graphic.identifier}", edit_graphic_path(graphic)
        - if current_user.role == "admin"
          %button.remove-graphic{ :data => { :page_id => @page.id, :graphic_id => graphic.id } } Remove
      .col-xs-5.graphics-list-images
        =image_tag(asset_path(graphic.image), class: graphic.identifier)
      .col-xs-1

app/views/pages/add_content.js.erb
$('#contents-list').html("<%= escape_javascript(render partial: 'contents_list', object: @page) %>");

app/views/pages/add_graphic.js.erb
$('#graphics-list').html("<%= escape_javascript(render partial: 'graphics_list', object: @page) %>");

app/views/pages/edit.html.haml
.row
  .col-xs-3
  .col-xs-6.admin-text
    =form_for @page do |f|
      %fieldset
        %legend Edit a Page
        =if @page.errors.any?
          .row
            .col-xs-12
              %h2 Errors:
              %ul
                =@page.errors.full_messages.each do |m|
                  %li=m
        .row
          .col-xs-4
            =f.label :title
          .col-xs-4
            =f.text_field :title
          .col-xs-4
        - if current_user.role == "admin"
          .row
            .col-xs-4
              =f.label :controller do
                Controller <small class="asterisk">*</small>
            .col-xs-4
              =f.text_field :controller, :required => true
            .col-xs-4
          .row
            .col-xs-4
              =f.label :action do
                Action <small class="asterisk">*</small>
            .col-xs-4
              =f.text_field :action, :required => true
            .col-xs-4
        .row
          .col-xs-12
            =f.submit "Update the Page"
        - if current_user.role == "admin"
          .row
            .col-xs-12
              %label.required-label
                %small.asterisk * required
  .col-xs-3
.row
  .col-xs-1
  .col-xs-5.admin-text#contents-list
    %h3 Page Contents
    =render partial: 'contents_list', object: @page
  .col-xs-5.admin-text#graphics-list
    %h3 Page Graphics
    =render partial: 'graphics_list', object: @page
  .col-xs-1
- if current_user.role == "admin"
  .row
    .col-xs-1
    .col-xs-5.admin-text
      %form
        %fieldset
          %legend Add a Content to This Page
          %select#contents-menu{:data => {:id => @page.id}}
            - @contents.each do |content|
              %option{:value => content.id} #{content.identifier}
          %button#add-content Add the Content
    .col-xs-5.admin-text
      %form
        %fieldset
          %legend Add a Graphic to This Page
          %select#graphics-menu{:data => {:id => @page.id}}
            - @graphics.each do |graphic|
              %option{:value => graphic.id} #{graphic.identifier}
          %button#add-graphic Add the Graphic
    .col-xs-1

app/views/pages/index.html.haml
.row
  .col-xs-12
    - column = 0
    - @pages.each do |page|
      - if column % 3 == 0
        .row
      .col-xs-4.admin-text
        .row
          .col-xs-12.pages-index-cell-header
            %h2=page.title
            %h5 #{page.controller}##{page.action}
        .row.pages-index-cell-display
          .col-xs-8
            %ul
              - page.contents.each do |content|
                %li
                  %p
                    =render inline: content.text
          .col-xs-4.pages-index-cell-graphics
            - page.graphics.each do |graphic|
              =image_tag(asset_path(graphic.image))
        .row
          .col-xs-12
            = button_to "Edit", edit_page_path(page.id), :method => :get
            - if current_user.role == "admin"
              = button_to "Delete", page, data: {confirm: "Are you sure you want to delete the page at #{page.controller}##{page.action}?"}, :method => :delete
      - column = column + 1

app/views/pages/new.html.haml
.row
  .col-xs-3
  .col-xs-6.admin-text
    =form_for @page do |f|
      %fieldset
        %legend Create a Page
        =if @page.errors.any?
          .row
            .col-xs-12
              %h2 Errors:
              %ul
                =@page.errors.full_messages.each do |m|
                  %li=m
        .row
          .col-xs-4
            =f.label :title
          .col-xs-4
            =f.text_field :title
          .col-xs-4
        .row
          .col-xs-4
            =f.label :controller do
              Controller <small class="asterisk">*</small>
          .col-xs-4
            =f.text_field :controller, :required => true
          .col-xs-4
        .row
          .col-xs-4
            =f.label :action do
              Action <small class="asterisk">*</small>
          .col-xs-4
            =f.text_field :action, :required => true
          .col-xs-4
        .row
          .col-xs-12
            =f.submit "Create Page"
        .row
          .col-xs-12
            %label.required-label
              %small.asterisk * required
  .col-xs-3

app/views/pages/remove_content.js.erb
$('#contents-list').html("<%= escape_javascript(render partial: 'contents_list', object: @page) %>");

app/views/pages/remove_graphic.js.erb
$('#graphics-list').html("<%= escape_javascript(render partial: 'graphics_list', object: @page) %>");